### Получить всех сотрудников
GET http://localhost:8080/employees
### Создать сотрудника 1
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "ivan",
  "lastName": "ivanov",
  "department": 1,
  "salary": 2000
}

### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "sergey",
  "lastName": "petrov",
  "department": 2,
  "salary": 8500
}
### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "andrey",
  "lastName": "sidorov",
  "department": 2,
  "salary": 1000
}
### Получение суммы зарплат сотрудников
GET http://localhost:8080/employees/salary/sum

### Получение средней зарплат сотрудников
GET http://localhost:8080/employees/salary/avr

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max

### Получение сотрудника с зарплатой выше средней
GET http://localhost:8080/employees/high-salary

### Получение списока сотрудников по департаменту
GET http://localhost:8080/department/1/employees

### Получение суммы зарплат по департаменту
GET http://localhost:8080/department/2/salary/sum

### Получение максимальной зарплаты по департаменту
GET http://localhost:8080/department/2/salary/max

### Получение минимальной зарплаты по департаменту
GET http://localhost:8080/department/2/salary/min

### Получение списока сотрудников сотрированных по отделам
GET  http://localhost:8080/department/employees